blank_issues_enabled: false
contact_links:
    - name: Help & Usage Questions
      url: https://www.reddit.com/r/grocy
      about: Please use the r/grocy subreddit for general help and usage questions
